# Generated by Django 5.2 on 2025-04-24 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
