# Generated by Django 5.2 on 2025-04-26 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0002_enrollment_updated_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='health_app.client'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('client', 'program')},
        ),
    ]
